App-Cmd: add test dep
Missing dependency identified by the CI:
  Error:  Can't locate Module/Pluggable/Object.pm in @INC (you may need
          to install the Module::Pluggable::Object module)

Log:
  https://gitlab.exherbo.org/tureba/arbor/-/jobs/3984/raw